[package]
name = "weather_icons"
version = "0.4.0"
authors = ["Matthew Klein <mklein994@gmail.com>"]
description = "An API to organize icons from https://weathericons.io"
documentation = "https://docs.rs/weather_icons"
license = "MIT"
edition = "2018"

[dependencies]
