use super::icon::Icon;
use std::fmt;

pub enum DripIcon {
    Cloud,
    CloudDrizzle,
    CloudDrizzleLightning,
    CloudDrizzleLightningMoon,
    CloudDrizzleLightningSun,
    CloudDrizzleLightningSunAlt,
    CloudDrizzleMoon,
    CloudDrizzleSun,
    CloudDrizzleSunAlt,
    CloudFog,
    CloudFogAlt,
    CloudFogMoon,
    CloudFogSun,
    CloudFogSunAlt,
    CloudHail,
    CloudHailLightning,
    CloudHailLightningMoon,
    CloudHailLightningSun,
    CloudHailLightningSunAlt,
    CloudHailMoon,
    CloudHailSun,
    CloudHailSunAlt,
    CloudLightning,
    CloudLightningMoon,
    CloudLightningSun,
    CloudLightningSunAlt,
    CloudMoon,
    CloudRain,
    CloudRainAlt,
    CloudRainAltMoon,
    CloudRainAltSun,
    CloudRainAltSunAlt,
    CloudRainLightning,
    CloudRainLightningMoon,
    CloudRainLightningSun,
    CloudRainLightningSunAlt,
    CloudRainMoon,
    CloudRainSun,
    CloudRainSunAlt,
    CloudSnow,
    CloudSnowMoon,
    CloudSnowSun,
    CloudSnowSunAlt,
    CloudSun,
    CloudSunAlt,
    CloudWind,
    CloudWindAlt,
    CloudWindAltMoon,
    CloudWindAltSun,
    CloudWindAltSunAlt,
    CloudWindMoon,
    CloudWindSun,
    CloudWindSunAlt,
    Clouds,
    CloudsMoon,
    CloudsSun,
    CloudsSunAlt,
    CompassEast,
    CompassNorth,
    CompassSouth,
    CompassWest,
    DegreesCelsius,
    DegreesFahrenheit,
    Drizzle,
    Flag,
    Fog,
    Hail,
    Lightning,
    Moon25,
    Moon50,
    Moon75,
    Moon100,
    MoonStars,
    Rain,
    Raindrop,
    Snow,
    Sun,
    SunEclipse,
    SunLow,
    SunLower,
    SunRise,
    SunSet,
    Thermometer25,
    Thermometer50,
    Thermometer75,
    Thermometer100,
    Tornado,
    Umbrella,
    UmbrellaDrizzle,
    Wet,
    Wind,
}

impl fmt::Display for DripIcon {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        use self::DripIcon::*;
        write!(
            f,
            "{}",
            match *self {
                Cloud => "a",
                CloudDrizzle => "b",
                CloudDrizzleLightning => "c",
                CloudDrizzleLightningMoon => "d",
                CloudDrizzleLightningSun => "e",
                CloudDrizzleLightningSunAlt => "f",
                CloudDrizzleMoon => "g",
                CloudDrizzleSun => "h",
                CloudDrizzleSunAlt => "i",
                CloudFog => "j",
                CloudFogAlt => "k",
                CloudFogMoon => "l",
                CloudFogSun => "m",
                CloudFogSunAlt => "n",
                CloudHail => "o",
                CloudHailLightning => "p",
                CloudHailLightningMoon => "q",
                CloudHailLightningSun => "r",
                CloudHailLightningSunAlt => "s",
                CloudHailMoon => "t",
                CloudHailSun => "u",
                CloudHailSunAlt => "v",
                CloudLightning => "w",
                CloudLightningMoon => "x",
                CloudLightningSun => "y",
                CloudLightningSunAlt => "z",
                CloudMoon => "A",
                CloudRain => "B",
                CloudRainAlt => "C",
                CloudRainAltMoon => "D",
                CloudRainAltSun => "E",
                CloudRainAltSunAlt => "F",
                CloudRainLightning => "G",
                CloudRainLightningMoon => "H",
                CloudRainLightningSun => "I",
                CloudRainLightningSunAlt => "J",
                CloudRainMoon => "K",
                CloudRainSun => "L",
                CloudRainSunAlt => "M",
                CloudSnow => "N",
                CloudSnowMoon => "O",
                CloudSnowSun => "P",
                CloudSnowSunAlt => "Q",
                CloudSun => "R",
                CloudSunAlt => "S",
                CloudWind => "T",
                CloudWindAlt => "U",
                CloudWindAltMoon => "V",
                CloudWindAltSun => "W",
                CloudWindAltSunAlt => "X",
                CloudWindMoon => "Y",
                CloudWindSun => "Z",
                CloudWindSunAlt => "0",
                Clouds => "1",
                CloudsMoon => "2",
                CloudsSun => "3",
                CloudsSunAlt => "4",
                CompassEast => "5",
                CompassNorth => "6",
                CompassSouth => "7",
                CompassWest => "8",
                DegreesCelsius => "9",
                DegreesFahrenheit => "!",
                Drizzle => "\"",
                Flag => "#",
                Fog => "$",
                Hail => "%",
                Lightning => "&",
                Moon25 => "'",
                Moon50 => "(",
                Moon75 => ")",
                Moon100 => "*",
                MoonStars => "+",
                Rain => ",",
                Raindrop => "-",
                Snow => ".",
                Sun => "/",
                SunEclipse => ":",
                SunLow => ";",
                SunLower => "<",
                SunRise => "=",
                SunSet => ">",
                Thermometer25 => "?",
                Thermometer50 => "@",
                Thermometer75 => "[",
                Thermometer100 => "]",
                Tornado => "^",
                Umbrella => "_",
                UmbrellaDrizzle => "`",
                Wet => "{",
                Wind => "|",
            }
        )
    }
}

impl From<Icon> for DripIcon {
    fn from(icon: Icon) -> Self {
        use DripIcon::*;
        match icon {
            Icon::Cloud => Cloud,
            Icon::Showers => CloudDrizzle,
            Icon::StormShowers => CloudDrizzleLightning,
            Icon::NightAltStormShowers => CloudDrizzleLightningMoon,
            Icon::DayStormShowers => CloudDrizzleLightningSun,
            Icon::NightStormShowers => CloudDrizzleLightningSunAlt,
            Icon::NightAltShowers => CloudDrizzleMoon,
            Icon::DayShowers => CloudDrizzleSun,
            Icon::NightShowers => CloudDrizzleSunAlt,
            Icon::Fog => CloudFog,
            Icon::NightFog => CloudFogMoon,
            Icon::DayFog => CloudFogSun,
            Icon::Hail => CloudHail,
            Icon::NightAltHail => CloudHailMoon,
            Icon::DayHail => CloudHailSun,
            Icon::NightHail => CloudHailSunAlt,
            Icon::NightAltLightning => CloudLightningMoon,
            Icon::DayLightning => CloudLightningSun,
            Icon::NightLightning => CloudLightningSunAlt,
            Icon::NightAltCloudy => CloudMoon,
            Icon::Rain => CloudRain,
            Icon::Sprinkle => CloudRainAlt,
            Icon::NightAltSprinkle => CloudRainAltMoon,
            Icon::DaySprinkle => CloudRainAltSun,
            Icon::NightSprinkle => CloudRainAltSunAlt,
            Icon::Thunderstorm => CloudRainLightning,
            Icon::NightAltThunderstorm => CloudRainLightningMoon,
            Icon::DayThunderstorm => CloudRainLightningSun,
            Icon::NightThunderstorm => CloudRainLightningSunAlt,
            Icon::NightAltRain => CloudRainMoon,
            Icon::DayRain => CloudRainSun,
            Icon::NightRain => CloudRainSunAlt,
            Icon::Snow => CloudSnow,
            Icon::NightAltSnow => CloudSnowMoon,
            Icon::DaySnow => CloudSnowSun,
            Icon::NightSnow => CloudSnowSunAlt,
            Icon::DayCloudy => CloudSun,
            Icon::NightCloudy => CloudSunAlt,
            Icon::CloudyGusts => CloudWind,
            Icon::CloudyWindy => CloudWindAlt,
            Icon::NightAltCloudyWindy => CloudWindAltMoon,
            Icon::DayCloudyWindy => CloudWindAltSun,
            Icon::NightCloudyWindy => CloudWindAltSunAlt,
            Icon::NightAltCloudyGusts => CloudWindMoon,
            Icon::NightCloudyGusts => CloudWindSunAlt,
            Icon::Cloudy => Clouds,
            Icon::DirectionRight => CompassEast,
            Icon::DirectionUp => CompassNorth,
            Icon::DirectionDown => CompassSouth,
            Icon::DirectionLeft => CompassWest,
            Icon::Celsius => DegreesCelsius,
            Icon::Fahrenheit => DegreesFahrenheit,
            Icon::SmallCraftAdvisory => Flag,
            Icon::Windy => Fog,
            Icon::Lightning => Lightning,
            Icon::Raindrop => Raindrop,
            Icon::SnowflakeCold => Snow,
            Icon::DaySunny => Sun,
            Icon::SolarEclipse => SunEclipse,
            Icon::HorizonAlt => SunLow,
            Icon::Horizon => SunLower,
            Icon::Sunrise => SunRise,
            Icon::Sunset => SunSet,
            Icon::Thermometer => Thermometer100,
            Icon::Tornado => Tornado,
            Icon::Umbrella => Umbrella,
            Icon::Raindrops => Wet,
            Icon::StrongWind => Wind,
            Icon::NightPartlyCloudy => CloudsSunAlt,
            Icon::DaySunnyOvercast => CloudsSun,
            Icon::NightClear => Moon75,
            _ => unimplemented!(),
        }
    }
}
